### ISSUE TITLE
Sharing decadal simulation outputs

### ISSUE THREAD

**Issue by shoyer** [neuralgcm/neuralgcm#103]
There is a request on Twitter to share our decadal simulation results -- is this something we might be able to do easily?

xref https://github.com/google-research/neuralgcm/issues/99

https://x.com/Chengfei_He/status/1815923052418310235

**Comment by yaniyuval** [comment]
Data from NeuralGCM simulations, including the 40-year runs used in the NeuralGCM paper, is now available at https://neuralgcm.readthedocs.io/en/latest/neuralgcm_datasets.html.
