### ISSUE TITLE
RuntimeError: Unable to Load libcudnn_engines_precompiled.so in JAX, Despite Setting Library Paths

### ISSUE THREAD

**Issue by heylsitan** [neuralgcm/neuralgcm#148]
I am encountering an issue when running my Python script with JAX. The error message indicates that it is unable to load libcudnn_engines_precompiled.so.9.5.1 or similar versions. Below is the error traceback I am seeing:

/data/groups/g1600002/home/heyongli/NeuralGCM/Neuralgcm.py:24: DeprecationWarning: Pickled array contains an aval with a named_shape attribute. This is deprecated and the code path supporting such avals will be removed. Please re-pickle the array.
  ckpt = pickle.load(f)
Unable to load any of {libcudnn_engines_precompiled.so.9.5.1, libcudnn_engines_precompiled.so.9.5, libcudnn_engines_precompiled.so.9, libcudnn_engines_precompiled.so}
Traceback (most recent call last):
  File "/data/groups/g1600002/home/heyongli/NeuralGCM/Neuralgcm.py", line 81, in <module>
    final_state, predictions = model.unroll(
                               ^^^^^^^^^^^^^
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_SUBLIBRARY_LOADING_FAILED

I have already downloaded the appropriate cuDNN libraries and configured the environment variables in .bashrc as follows:
export LD_LIBRARY_PATH=/opt/app/nvidia/550.54.14/lib:$LD_LIBRARY_PATH
export CUDNN_HOME=/data/groups/lzu_public/home/heyongli/my_lib/cudnn-linux-x86_64-9.5.1.17_cuda12-archive
export LD_LIBRARY_PATH=$CUDNN_HOME/lib:$LD_LIBRARY_PATH

Despite this, I continue to see the error about not being able to load libcudnn_engines_precompiled.so.

Does anyone know how to resolve this issue? Is there anything I need to check or update to help JAX find the required libcudnn files?

Thanks in advance for your help!

**Comment by shoyer** [comment]
Unfortunately, this looks like a JAX installation issue, unrelated to NeuralGCM.
