### ISSUE TITLE
Can't download neural_gcm_dynamic_forcing_deterministic_2_8_deg.pkl by gsutil anymore

### ISSUE THREAD

**Issue by weatherforecasterwhai** [neuralgcm/neuralgcm#186]
When using gsutil like this:
**gsutil -m cp -R gs://gresearch/neuralgcm/04_30_2024/neural_gcm_dynamic_forcing_deterministic_2_8_deg.pkl .**
I always got this result:
**INFO 1212 16:55:00.384891 retry_util.py] Retrying request, attempt #1...**

I've downloaded 0.7 and 1.4 .pkl files before, but withou 2.8 file.
Would somebody help me? What's more, I'm in China. Thank you.

**Comment by shoyer** [comment]
The checkpoint is still publically available in the Google cloud bucket. I can download it without authentication in the US.

I'm afraid I don't know what the issue might be for downloading from China.

**Comment by weatherforecasterwhai** [comment]
Thank you! What a shame for the Great wall of China!
By the way, in #188 , It seems, 04_30_2024 checkpoint files are not compatible with the latest neuralgcm and dinosaur. 
Please take a look and check!
