### ISSUE TITLE
04_30_2024  .pkl file is uncompatible with latest neuralgcm and dinosaur version

### ISSUE THREAD

**Issue by weatherforecasterwhai** [neuralgcm/neuralgcm#188]
The 04_30_2024  .pkl file runs out these error:
**'tsv110' is not a recognized processor for this target (ignoring processor)
...
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!**

And, I can't use gsutil to download or list the neuralgcm diretories anymore as in #186 .

Do you have new .pkl files in gsutil?  Thank you!

**Comment by shoyer** [comment]
I'm not sure about this error message, but I recommend trying again with the latest (1.1.0) NeuralGCM release, which fixes an incompatibility issue between neuralgcm 1.0.0 and dinosaur 1.1.1.

**Comment by weatherforecasterwhai** [comment]
Yes, I've tried the latest neuralgcm 1.1.0 and dinosaur 1.1.1, and the checkpoint file still reads with the same errors:
**'tsv110' is not a recognized processor for this target (ignoring processor)
'+crc' is not a recognized feature for this target (ignoring feature)
'+fp-armv8' is not a recognized feature for this target (ignoring feature)
'+lse' is not a recognized feature for this target (ignoring feature)
'+neon' is not a recognized feature for this target (ignoring feature)
'+sha2' is not a recognized feature for this target (ignoring feature)
'tsv110' is not a recognized processor for this target (ignoring processor)**
the same errors recycle and end with :
**LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
core dumped**

**Comment by shoyer** [comment]
Can you share a full code example, and  the traceback message? I'm not sure, but this looks like it may be a broken JAX installation for reasons unrelated to NeuralGCM.

**Comment by weatherforecasterwhai** [comment]
Thank you for your attention and help!
Because gsutil is out of connection in China, so I've downloaded the ERA5 high and surface data as era5.nc and gcm_surface.nc as input. The input files worked in the old version of neuralgcm and dinosaur weeks ago.

After importing libraries, the full codes are almost the same with your documents:

**model_name ='neural_gcm_dynamic_forcing_deterministic_0_7_deg.pkl'

with open(model_name,'rb') as f:
    ckpt = pickle.load(f)

var_dict = {
    'siconc':'sea_ice_cover', 
    'sst':'sea_surface_temperature',
    'u':'u_component_of_wind', 
    'v':'v_component_of_wind', 
    'z':'geopotential', 
    't':'temperature', 
    'q':'specific_humidity', 
    'ciwc':'specific_cloud_ice_water_content', 
    'clwc':'specific_cloud_liquid_water_content',
}
new_inputs_to_units_mapping={
        'u':'meter/second',
        'v':'meter/second',
        't':'kelvin',
        'z':'m**2 s**-2',
        'sim_time':'dimensionless',
        'tracers':{'specific_humidity':'dimensionless',
            'specific_cloud_liquid_water_content':'dimensionless',
            'specific_cloud_ice_water_content':'dimensionless',
            },
        'diagnostics':{'P_minus_E_cumulative':'kg/(meter**2)'}
        }

new_model_config_str = '\n'.join([
    ckpt['model_config_str'],
    f'DimensionalLearnedPrimitiveToWeatherbenchDecoder.inputs_to_units_mapping = {new_inputs_to_units_mapping}',
    'DimensionalLearnedPrimitiveToWeatherbenchDecoder.diagnostics_module = @NodalModelDiagnosticsDecoder',
    'StochasticPhysicsParameterizationStep.diagnostics_module = @PrecipitationMinusEvaporationDiagnostics',
    'PrecipitationMinusEvaporationDiagnostics.method = "cumulative"',
    'PrecipitationMinusEvaporationDiagnostics.moisture_species =  ("specific_humidity", "specific_cloud_liquid_water_content", "specific_cloud_ice_water_content")',])
ckpt['model_config_str'] = new_model_config_str

neuralgcm_vars = [
    'u_component_of_wind',
    'v_component_of_wind',
    'geopotential',
    'temperature',
    'specific_humidity',
    'specific_cloud_ice_water_content',
    'specific_cloud_liquid_water_content',
    'sea_surface_temperature',
    'sea_ice_cover',
]

neural_gcm_model =neuralgcm.PressureLevelModel.from_checkpoint(ckpt)
path=['./era5.nc','./gcm_surface.nc']
era5_surface=xarray.open_dataset(path[1]).sel(valid_time=['2022-08-05 00:00:00','2022-08-06 00:00:00'])
era5_high=xarray.open_dataset(path[0]).sel(valid_time=['2022-08-05 00:00:00','2022-08-06 00:00:00'])

full_era5=xarray.merge([era5_high,era5_surface])

full_era5=(full_era5.rename_vars(var_dict).rename_dims({"valid_time":"time"}).rename_vars({"valid_time":"time"}).drop_vars(["expver","number"],errors="ignore"))
full_era5=(full_era5.rename_dims({"pressure_level":"level"}).rename_vars({"pressure_level":"level"}))
full_era5_ds = full_era5[neural_gcm_model.input_variables+neural_gcm_model.forcing_variables] 

era5_grid = spherical_harmonic.Grid(
    latitude_nodes=full_era5_ds.sizes['latitude'],
    longitude_nodes=full_era5_ds.sizes['longitude'],
    latitude_spacing=xarray_utils.infer_latitude_spacing(full_era5_ds.latitude),
    longitude_offset=xarray_utils.infer_longitude_offset(full_era5_ds.longitude),
)

target_grid = neural_gcm_model.data_coords.horizontal
regridder = horizontal_interpolation.ConservativeRegridder(
    era5_grid, target_grid,skipna=True)

era5_ds=full_era5_ds
eval_ds = xarray_utils.regrid(era5_ds,regridder)**

Then, the regrid outputs error as above.

**Comment by shoyer** [comment]
Is there a Python traceback? I don't see the Python error message.

**Comment by weatherforecasterwhai** [comment]
Why are you always online helping us, sir? Please sleep enough time!

I only got these:

Pickled array contains an aval with a named_shape attribute. This is deprecated and the code path supporting such avals will be removed. Please re-pickle the array.
This is output after reading the pickle file.

And the regriding error:
'tsv110' is not a recognized processor for this target (ignoring processor)
'+crc' is not a recognized feature for this target (ignoring feature)
'+fp-armv8' is not a recognized feature for this target (ignoring feature)
'+lse' is not a recognized feature for this target (ignoring feature)
'+neon' is not a recognized feature for this target (ignoring feature)
'+sha2' is not a recognized feature for this target (ignoring feature)
'tsv110' is not a recognized processor for this target (ignoring processor)
the same errors recycle and end with :
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
core dumped

**Comment by weatherforecasterwhai** [comment]
Why are you always online helping us, sir? Please sleep enough time!

I only got these:

Pickled array contains an aval with a named_shape attribute. This is deprecated and the code path supporting such avals will be removed. Please re-pickle the array.
This is output after reading the pickle file.

And the regriding error:
'tsv110' is not a recognized processor for this target (ignoring processor)
'+crc' is not a recognized feature for this target (ignoring feature)
'+fp-armv8' is not a recognized feature for this target (ignoring feature)
'+lse' is not a recognized feature for this target (ignoring feature)
'+neon' is not a recognized feature for this target (ignoring feature)
'+sha2' is not a recognized feature for this target (ignoring feature)
'tsv110' is not a recognized processor for this target (ignoring processor)
the same errors recycle and end with :
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
core dumped

**Comment by shoyer** [comment]
The message about "pickle" is only a warning, it should not effect correctness. It should be fixed if you use the new checkpoints from `gs://neuralgcm/models` described here https://neuralgcm.readthedocs.io/en/latest/checkpoints.html

I think something else is wrong with your JAX installation rather than with NeuralGCM. Your error message looks similar to this: https://github.com/jax-ml/jax/issues/9670

**Comment by weatherforecasterwhai** [comment]
Great! Thank you for mentioning your newest version!
I'll learn your newest paper first.

You know, I can't use gsutil anymore in China. I beg for your more help: 
Would you please send these three checkpoints to me? 
v1_precip/stochastic_precip_2_8_deg.pkl,
v1_precip/stochastic_evap_2_8_deg.pkl
and v1/deterministic_2_8_deg.pkl.

My email is wanghai860115@126.com.
Really really thank you!
