### ISSUE TITLE
Would you please explain the Transformer and attention mentioned in neuralgcm codes?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [neuralgcm/neuralgcm#192]
Your excellent NeuralGCM paper just mentioned Multi-Layer Perception used in most parts of learning, then I found at least these python files mentioned  Transformer and attention. Would you please give more explain:
********************************************************************************************************
initializers.py:        Useful if instantiating multi-headed attention weights.
layers.py:  """**Network that uses attention mechanism across vertical levels.**
layers.py:  which case the network uses `inputs` and performs self-attention calculation
layers.py:  calculations for all attention blocks. If `positional_encoding` is provided,
layers.py:  then it is used to produce the first set of queries in an attention block.
layers.py:    num_heads: number of attention heads in each attention layer.
layers.py:    key_size: size of key/query vectors to use for computing attention scores.
layers.py:      # apply layer norm before the attention block, as in GTrXL.
layers.py:      # attend to `latents` if in decoding stage, otherwise use self-attention.
layers.py:      # connects residual updates from attention layer.
layers_test.py:          inputs_shape=(3, 12),  # self-attention on d=3 inputs, returning 4.

layers.py:class LevelTransformer(hk.Module):
layers.py:  This network is a simple variation of a transformer architecture. It is
layers.py:  resembling GTrXL transformer from https://arxiv.org/pdf/1910.06764.pdf.
layers.py:    n_layers: number of transformer blocks in the network.
layers.py:              ' Specify projection module in the transformer.'
layers.py:    """Applies transformer layer to inputs. See class docstring for details."""
layers_test.py:          extra_config_str='LevelTransformer.skip_final_projection = True',
layers_test.py:          extra_config_str='LevelTransformer.input_projection_net = None',
layers_test.py:  def test_level_transformer_shape(
layers_test.py:    """Tests that LevelTransformer outputs have expected shapes."""
layers_test.py:        'layer_forward.layer = @LevelTransformer',
layers_test.py:        'LevelTransformer.n_layers = 1',
layers_test.py:        'LevelTransformer.latent_size = 8',
layers_test.py:        'LevelTransformer.num_heads = 2',
layers_test.py:        'LevelTransformer.key_size = 4',
mappings.py:class NodalVolumeTransformerMapping(hk.Module):
mappings.py:  encoding arguments to the underlying transformer networks. Inputs are
mappings.py:  to transformer towers. The output of the NN is expected to have shape
mappings.py:      encoder_transformer_tower_factory: Tower = gin.REQUIRED,
mappings.py:      decoder_transformer_tower_factory: Tower = gin.REQUIRED,
mappings.py:    self.encoder_tower = encoder_transformer_tower_factory(latent_size)
mappings.py:    self.decoder_tower = decoder_transformer_tower_factory(output_size)
mappings_test.py:          mapping_name='NodalVolumeTransformerMapping',
mappings_test.py:    long_name = 'NodalVolumeTransformerMapping'
mappings_test.py:        f'{long_name}.encoder_transformer_tower_factory = @MappingsTowerMock',
mappings_test.py:        f'{long_name}.decoder_transformer_tower_factory = @MappingsTowerMock',
towers.py:class ColumnTransformerTower(ColumnTower):
towers.py:  """Same as ColumnTower, but passes additional transformer inputs."""
********************************************************************************************************

**Comment by shoyer** [comment]
These are experimental models that tried in the process of developing NeuralGCM. They are much slower than the MLP models and we did not find them to have consistent advantages in performance.
